import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const Terms = () => {
  const [activeSection, setActiveSection] = useState('terms');

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden">
          {/* Header */}
          <div className="bg-gradient-to-r from-indigo-500 to-purple-600 px-8 py-6">
            <h1 className="text-3xl font-bold text-white">
              Terms of Service & Privacy Policy
            </h1>
            <p className="text-indigo-100 mt-2">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </div>

          {/* Navigation */}
          <div className="border-b border-gray-200 dark:border-gray-700">
            <nav className="flex space-x-8 px-8">
              {['terms', 'privacy', 'cookies'].map((section) => (
                <button
                  key={section}
                  onClick={() => setActiveSection(section)}
                  className={`py-4 text-sm font-medium border-b-2 transition-colors ${
                    activeSection === section
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400'
                      : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
                  }`}
                >
                  {section === 'terms' ? 'Terms of Service' : 
                   section === 'privacy' ? 'Privacy Policy' : 'Cookie Policy'}
                </button>
              ))}
            </nav>
          </div>

          {/* Content */}
          <div className="px-8 py-8 prose prose-gray dark:prose-invert max-w-none">
            {activeSection === 'terms' && <TermsContent />}
            {activeSection === 'privacy' && <PrivacyContent />}
            {activeSection === 'cookies' && <CookiesContent />}
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-8">
          <Link
            to="/"
            className="text-indigo-600 dark:text-indigo-400 hover:underline"
          >
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
};

const TermsContent = () => (
  <div className="space-y-6">
    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Terms of Service</h2>
    
    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        By accessing and using Demotivation Station, you accept and agree to be bound by the terms and provision of this agreement.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Service Description</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        Demotivation Station is an AI-powered platform that generates demotivational and motivational content for entertainment purposes. The service includes:
      </p>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mt-2 space-y-1">
        <li>AI-generated demotivational messages</li>
        <li>Voice synthesis capabilities</li>
        <li>Chat functionality</li>
        <li>User accounts and preferences</li>
        <li>Premium subscription features</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. User Responsibilities</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        Users agree to:
      </p>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mt-2 space-y-1">
        <li>Use the service for lawful purposes only</li>
        <li>Not attempt to harm or disrupt the service</li>
        <li>Respect intellectual property rights</li>
        <li>Not share account credentials</li>
        <li>Report any abuse or violations</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Content and Usage</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        All content generated by our AI is for entertainment purposes. Users retain rights to their inputs, while generated content may be used for service improvement and analytics.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Limitation of Liability</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        Demotivation Station is provided "as is" without warranties. We are not liable for any damages arising from the use of our service.
      </p>
    </section>
  </div>
);

const PrivacyContent = () => (
  <div className="space-y-6">
    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Privacy Policy</h2>
    
    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Information We Collect</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        We collect the following types of information:
      </p>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mt-2 space-y-1">
        <li><strong>Account Information:</strong> Email, name, and authentication data</li>
        <li><strong>Usage Data:</strong> How you interact with our service</li>
        <li><strong>Generated Content:</strong> Inputs and outputs for service improvement</li>
        <li><strong>Technical Data:</strong> IP address, browser type, device information</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">How We Use Information</h3>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
        <li>To provide and improve our services</li>
        <li>To process payments and manage subscriptions</li>
        <li>To send important updates and notifications</li>
        <li>To analyze usage patterns and enhance user experience</li>
        <li>To prevent fraud and ensure security</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Data Sharing</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        We do not sell your personal data. We may share information with:
      </p>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mt-2 space-y-1">
        <li>Service providers (payment processors, analytics)</li>
        <li>Legal authorities when required by law</li>
        <li>Business partners with your consent</li>
      </ul>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Your Rights</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        You have the right to:
      </p>
      <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mt-2 space-y-1">
        <li>Access your personal data</li>
        <li>Correct inaccurate information</li>
        <li>Delete your account and data</li>
        <li>Export your data</li>
        <li>Opt-out of marketing communications</li>
      </ul>
    </section>
  </div>
);

const CookiesContent = () => (
  <div className="space-y-6">
    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Cookie Policy</h2>
    
    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">What Are Cookies</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        Cookies are small text files stored on your device when you visit our website. They help us provide a better user experience.
      </p>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Types of Cookies We Use</h3>
      <div className="space-y-4">
        <div>
          <h4 className="font-semibold text-gray-900 dark:text-white">Essential Cookies</h4>
          <p className="text-gray-700 dark:text-gray-300 text-sm">
            Required for the website to function properly, including authentication and security.
          </p>
        </div>
        <div>
          <h4 className="font-semibold text-gray-900 dark:text-white">Analytics Cookies</h4>
          <p className="text-gray-700 dark:text-gray-300 text-sm">
            Help us understand how users interact with our site to improve our services.
          </p>
        </div>
        <div>
          <h4 className="font-semibold text-gray-900 dark:text-white">Preference Cookies</h4>
          <p className="text-gray-700 dark:text-gray-300 text-sm">
            Remember your settings and preferences like theme and language.
          </p>
        </div>
      </div>
    </section>

    <section>
      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Managing Cookies</h3>
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        You can control cookies through your browser settings. Note that disabling essential cookies may affect website functionality.
      </p>
    </section>
  </div>
);

export default Terms;
