import React, { useState, useRef } from 'react';
import { Link } from 'react-router-dom';

const VoiceGenerator = () => {
  const [userInput, setUserInput] = useState('');
  const [selectedVoice, setSelectedVoice] = useState(null);
  const [generatedMessage, setGeneratedMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [speaking, setSpeaking] = useState(false);
  
  // New state variables for modern features
  const [inputMode, setInputMode] = useState('typing'); // 'typing', 'voice', 'chat'
  const [isRecording, setIsRecording] = useState(false);
  const [chatHistory, setChatHistory] = useState([]);

  const synth = useRef(window.speechSynthesis);

  const voices = [
    { id: 'gordon-ramsay', name: 'Gordon Ramsay', description: 'Harsh kitchen reality' },
    { id: 'simon-cowell', name: 'Simon Cowell', description: 'Brutal talent judge' },
    { id: 'drill-sergeant', name: 'Drill Sergeant', description: 'Military motivation killer' },
    { id: 'disappointed-parent', name: 'Disappointed Parent', description: 'Ultimate guilt trip' },
    { id: 'existential-philosopher', name: 'Nihilistic Philosopher', description: 'Questions everything' },
    { id: 'sarcastic-teenager', name: 'Sarcastic Teenager', description: 'Eye-rolling expert' },
    { id: 'corporate-boss', name: 'Corporate Boss', description: 'Dream crusher extraordinaire' },
    { id: 'reality-tv-host', name: 'Reality TV Host', description: 'Eliminates hope efficiently' }
  ];

  const generateMessage = async () => {
    if (!userInput.trim() || !selectedVoice) {
      setError('Please enter a message and select a voice');
      return;
    }

    setLoading(true);
    setError('');
    
    try {
      const response = await fetch('http://localhost:5000/api/generate-demotivation', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userInput: userInput.trim(),
          voiceStyle: selectedVoice.id
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate demotivation message');
      }

      const data = await response.json();
      setGeneratedMessage(data.message);
    } catch (err) {
      setError(err.message || 'An error occurred while generating the message');
    } finally {
      setLoading(false);
    }
  };

  const speakMessage = () => {
    if (!generatedMessage || speaking) return;
    
    setSpeaking(true);
    
    // Cancel any ongoing speech
    synth.current.cancel();
    
    const utterance = new SpeechSynthesisUtterance(generatedMessage);
    utterance.rate = 0.9;
    utterance.pitch = 0.8;
    utterance.volume = 1.0;
    
    // Try to find a suitable voice
    const availableVoices = synth.current.getVoices();
    if (availableVoices.length > 0) {
      // Prefer English voices
      const englishVoice = availableVoices.find(voice => 
        voice.lang.startsWith('en') && voice.name.toLowerCase().includes('male')
      ) || availableVoices.find(voice => voice.lang.startsWith('en'));
      
      if (englishVoice) {
        utterance.voice = englishVoice;
      }
    }
    
    utterance.onend = () => setSpeaking(false);
    utterance.onerror = () => setSpeaking(false);
    
    synth.current.speak(utterance);
  };

  const shareMessage = () => {
    if (navigator.share && generatedMessage) {
      navigator.share({
        title: 'Voice Demotivation',
        text: `"${generatedMessage}" - Generated by BrutualHQ`,
        url: window.location.href
      });
    } else {
      // Fallback: copy to clipboard
  navigator.clipboard.writeText(`"${generatedMessage}" - Generated by BrutualHQ`);
  alert('Message copied to clipboard!');
    }
  };

  // Voice input functionality
  const startVoiceInput = () => {
    if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) {
      setError('Voice input not supported in your browser');
      return;
    }

    setIsRecording(true);
    setError('');

    const recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
    recognition.continuous = false;
    recognition.interimResults = false;
    recognition.lang = 'en-US';

    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;
      setUserInput(prev => prev + (prev ? ' ' : '') + transcript);
      setIsRecording(false);
    };

    recognition.onerror = (event) => {
      setError('Voice input error: ' + event.error);
      setIsRecording(false);
    };

    recognition.onend = () => {
      setIsRecording(false);
    };

    recognition.start();
  };

  // Chat functionality
  const sendChatMessage = (message) => {
    if (!message.trim()) return;
    
    const newMessage = {
      id: Date.now(),
      text: message,
      sender: 'user',
      timestamp: new Date()
    };
    
    setChatHistory(prev => [...prev, newMessage]);
    
    // Auto-generate demotivation response
    setTimeout(() => {
      const responses = [
        "Let me crush that dream for you...",
        "Oh, another unrealistic goal? Interesting.",
        "I see delusion is strong with this one.",
        "Reality check incoming...",
        "Time to lower those expectations."
      ];
      
      const botResponse = {
        id: Date.now() + 1,
        text: responses[Math.floor(Math.random() * responses.length)],
        sender: 'bot',
        timestamp: new Date()
      };
      setChatHistory(prev => [...prev, botResponse]);
      
      // Set the message for voice generation
      setUserInput(message);
    }, 1500);
  };

  const clearChat = () => {
    setChatHistory([]);
  };

  const randomVoice = () => {
    const randomIndex = Math.floor(Math.random() * voices.length);
    setSelectedVoice(voices[randomIndex]);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Title */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Voice Demotivation Studio
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Transform your thoughts into crushing reality checks with AI-powered celebrity voices
          </p>
        </div>

        {/* Input Mode Toggle */}
        <div className="flex justify-center mb-8">
          <div className="bg-white rounded-xl p-2 shadow-lg border border-gray-200">
            {['typing', 'voice', 'chat'].map((mode) => (
              <button
                key={mode}
                onClick={() => setInputMode(mode)}
                className={`px-6 py-3 rounded-lg font-medium transition-all duration-200 ${
                  inputMode === mode
                    ? 'bg-indigo-600 text-white shadow-md'
                    : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50'
                }`}
              >
                {mode === 'typing' && '✍️ Type'}
                {mode === 'voice' && '🎤 Voice'}
                {mode === 'chat' && '💬 Chat'}
              </button>
            ))}
          </div>
        </div>

        {/* Main Content Grid */}
        <div className={`grid gap-8 ${inputMode === 'chat' ? 'lg:grid-cols-2' : 'lg:grid-cols-1'}`}>
          
          {/* Chat History (only visible in chat mode) */}
          {inputMode === 'chat' && (
            <div className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
                <h3 className="text-lg font-semibold text-gray-900">Chat History</h3>
                <button
                  onClick={clearChat}
                  className="px-3 py-1 text-sm text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md hover:bg-gray-50"
                >
                  Clear
                </button>
              </div>
              <div className="h-96 overflow-y-auto p-6">
                {chatHistory.length === 0 ? (
                  <div className="flex items-center justify-center h-full text-gray-500">
                    Start a conversation to see your chat history
                  </div>
                ) : (
                  <div className="space-y-4">
                    {chatHistory.map(msg => (
                      <div
                        key={msg.id}
                        className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        <div
                          className={`max-w-xs lg:max-w-md px-4 py-2 rounded-2xl ${
                            msg.sender === 'user'
                              ? 'bg-indigo-600 text-white'
                              : 'bg-gray-100 text-gray-900'
                          }`}
                        >
                          {msg.text}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Main Input Panel */}
          <div className="bg-white rounded-2xl shadow-xl border border-gray-200 p-8">
            {/* Input Section */}
            {inputMode === 'typing' && (
              <div className="mb-8">
                <label className="block text-lg font-semibold text-gray-900 mb-4">
                  Enter your message
                </label>
                <textarea
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  placeholder="Type something optimistic that needs crushing..."
                  className="w-full h-32 px-4 py-3 border-2 border-gray-300 rounded-xl resize-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors"
                />
              </div>
            )}

            {inputMode === 'voice' && (
              <div className="mb-8 text-center">
                <div className={`border-2 rounded-xl p-8 mb-4 transition-colors ${
                  isRecording ? 'border-red-500 bg-red-50' : 'border-gray-300 bg-gray-50'
                }`}>
                  <div className={`text-6xl mb-4 ${isRecording ? 'text-red-500' : 'text-gray-400'}`}>
                    🎤
                  </div>
                  <p className={`text-lg mb-4 ${isRecording ? 'text-red-600' : 'text-gray-600'}`}>
                    {isRecording ? 'Listening... Speak your delusions' : 'Click to start voice input'}
                  </p>
                  <button
                    onClick={startVoiceInput}
                    disabled={isRecording}
                    className={`px-6 py-3 rounded-xl font-semibold transition-colors ${
                      isRecording 
                        ? 'bg-gray-400 text-gray-200 cursor-not-allowed' 
                        : 'bg-indigo-600 hover:bg-indigo-700 text-white'
                    }`}
                  >
                    {isRecording ? 'Recording...' : 'Start Recording'}
                  </button>
                </div>
                {userInput && (
                  <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-left">
                    <strong>Transcribed:</strong> {userInput}
                  </div>
                )}
              </div>
            )}

            {inputMode === 'chat' && (
              <div className="mb-8">
                <div className="flex gap-3">
                  <input
                    type="text"
                    value={userInput}
                    onChange={(e) => setUserInput(e.target.value)}
                    placeholder="Type your message..."
                    className="flex-1 px-4 py-3 border-2 border-gray-300 rounded-full focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors"
                    onKeyPress={(e) => {
                      if (e.key === 'Enter') {
                        sendChatMessage(userInput);
                        setUserInput('');
                      }
                    }}
                  />
                  <button
                    onClick={() => {
                      sendChatMessage(userInput);
                      setUserInput('');
                    }}
                    className="bg-indigo-600 hover:bg-indigo-700 text-white rounded-full w-12 h-12 flex items-center justify-center transition-colors"
                  >
                    ➤
                  </button>
                </div>
              </div>
            )}

            {/* Voice Selection */}
            <div className="mb-8">
              <label className="block text-lg font-semibold text-gray-900 mb-4">
                Choose your demotivator
              </label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                {voices.map((voice, index) => (
                  <button
                    key={index}
                    onClick={() => setSelectedVoice(voice)}
                    className={`p-4 border-2 rounded-xl text-left transition-all ${
                      selectedVoice?.name === voice.name
                        ? 'border-indigo-500 bg-indigo-50'
                        : 'border-gray-300 hover:border-gray-400 bg-white'
                    }`}
                  >
                    <div className={`font-semibold mb-1 ${
                      selectedVoice?.name === voice.name ? 'text-indigo-700' : 'text-gray-900'
                    }`}>
                      {voice.name}
                    </div>
                    <div className="text-sm text-gray-600">
                      {voice.description}
                    </div>
                  </button>
                ))}
              </div>
              <button
                onClick={randomVoice}
                className="w-full p-3 border-2 border-dashed border-indigo-400 text-indigo-600 rounded-xl font-semibold hover:bg-indigo-50 transition-colors"
              >
                🎲 Surprise me with a random voice
              </button>
            </div>

            {/* Generate Button */}
            <button
              onClick={generateMessage}
              disabled={loading || !userInput.trim() || !selectedVoice}
              className={`w-full py-4 rounded-xl text-lg font-bold transition-all ${
                loading || !userInput.trim() || !selectedVoice
                  ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                  : 'bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white shadow-lg hover:shadow-xl'
              }`}
            >
              {loading ? 'Crushing your dreams...' : '💀 Generate Demotivation'}
            </button>

            {/* Error Display */}
            {error && (
              <div className="mt-6 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl">
                {error}
              </div>
            )}

            {/* Generated Message Display */}
            {generatedMessage && (
              <div className="mt-8 bg-gradient-to-r from-red-50 to-red-100 border-2 border-red-300 rounded-xl p-6">
                <h3 className="text-lg font-bold text-red-700 mb-3">
                  Your Demotivation Message:
                </h3>
                <p className="text-gray-800 text-lg italic mb-4">
                  "{generatedMessage}"
                </p>
                <div className="flex gap-3">
                  <button
                    onClick={speakMessage}
                    disabled={speaking}
                    className={`px-4 py-2 rounded-lg font-semibold transition-colors ${
                      speaking 
                        ? 'bg-gray-400 text-gray-200 cursor-not-allowed' 
                        : 'bg-green-600 hover:bg-green-700 text-white'
                    }`}
                  >
                    {speaking ? '🔊 Speaking...' : '🔊 Play Voice'}
                  </button>
                  <button
                    onClick={shareMessage}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    📤 Share
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default VoiceGenerator;